# SPDX-FileCopyrightText: 2023 kinduff
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- block:
    - when: linkding_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: linkding_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-linkding
    - install-all
    - install-linkding

- block:
    - when: not linkding_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-linkding
